version: '3.8'

services:
  n8n-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n_worker_custom
    restart: unless-stopped
    command: n8n worker
    environment:
      - N8N_DISABLE_UI=true
      - EXECUTIONS_MODE=queue
      - QUEUE_MODE=redis
      - N8N_RUNNERS_ENABLED=true

      # PostgreSQL
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-sc808gwwcck0ggwcksw4k8ck
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_data
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=J@W8zqK7m3RuP#sN

      # Redis
      - QUEUE_BULL_REDIS_HOST=redis-okg8ckoo04gg4sws4w84owcc
      - QUEUE_BULL_REDIS_PORT=6379

      # Безопасность
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ENCRYPTION_KEY=Bz42RxhZ8MHrY+N57uRYWl1DFbJZsIH2W+xIYyzOYg8=

      # Разрешаем доступ к внешним библиотекам
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true

    networks:
      - coolify

networks:
  coolify:
    external: true
    name: coolify
